"""Add AuditLog model and profile updates

Revision ID: 436e2ca08d41
Revises: 9ca54a4e34ff
Create Date: 2024-06-13 01:30:22.064292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '436e2ca08d41'
down_revision = '9ca54a4e34ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit_log')
    # ### end Alembic commands ###
